server:
  port: 23213  # 服务器端口

spring:
  mvc:
    servlet:
      load-on-startup: 100  # Servlet加载时的启动顺序

  # 数据库的相关配置
  datasource:
    url: jdbc:postgresql://192.168.1.10:32297/kongyu?currentSchema=public&stringtype=unspecified  # 数据库连接URL
    username: postgres  # 数据库用户名
    password: Lingo@local_postgresql_5432  # 数据库密码
    driver-class-name: org.postgresql.Driver  # MySQL数据库驱动类
    type: com.alibaba.druid.pool.DruidDataSource  # 使用Druid数据源

    # Druid连接池配置 https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    druid:
      initial-size: 10  # 初始化连接池大小
      min-idle: 10  # 最小空闲连接数
      max-active: 1000  # 最大活跃连接数
      max-wait: 10000  # 获取连接的最大等待时间，单位毫秒

# Mybatis Flex的配置 https://mybatis-flex.com/zh/base/configuration.html
mybatis-flex:
  global-config:
    print-banner: false